image: node:12.18.3

pipelines:
  branches:
    develop:
      - step:
          name: "Create artifact"
          script:
            - apt-get update
            - apt-get install -y zip
            # Necessary to build Strapi Admin
            - npm ci
            # Build Strapi Admin so it's included in app
            - npm run build
            # Remove node_modules to avoid any AWS EBS problems
            # Note: AWS EBS will install dependencies itself
            - rm -rf ./node_modules
            - zip -r application.zip .
          artifacts:
            - application.zip
      - step:
          name: "Deploy to Beanstalk"
          deployment: development
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: application.zip
                WAIT: "true"
    master:
      - step:
          name: "Create artifact"
          script:
            - apt-get update
            - apt-get install -y zip
            # Necessary to build Strapi Admin
            - npm ci
            # Build Strapi Admin so it's included in app
            - npm run build
            # Remove node_modules to avoid any AWS EBS problems
            # Note: AWS EBS will install dependencies itself
            - rm -rf ./node_modules
            - zip -r application.zip .
          artifacts:
            - application.zip
      - step:
          name: "Deploy to Beanstalk"
          deployment: production
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: application.zip
                WAIT: "true"
